CREATE DATABASE IF NOT EXISTs PanneauRAM CHARACTER SET 'utf8';

USE PanneauRAM;

DROP TABLE Authentification;
DROP TABLE Rapport;

CREATE TABLE IF NOT EXISTS Authentification(
  id SMALLINT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(25) NOT NULL,
  Password VARCHAR(25) NOT NULL,
  NiveauDroit SMALLINT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Rapport(
  LogID INT NOT NULL,
  Type VARCHAR(10) NOT NULL,
  UserLogin VARCHAR(25) NOT NULL,
  ReqTime DATETIME,
  INFO TEXT NOT NULL,
  PRIMARY KEY (LogID)
)
ENGINE = InnoDB;
